language: android
android:
  components:
  - android-22
  - build-tools-22.0.1
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository
before_install:
- openssl aes-256-cbc -K $encrypted_b5b10b36994f_key -iv $encrypted_b5b10b36994f_iv
  -in keys.tar.enc -out keys.tar -d
- tar xvf keys.tar
- mv madfau.keystore app/
script: "./gradlew assembleDebug"
