language: android
android:
  components:
  - android-22
  - build-tools-22.0.1
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository
script: "./gradlew assembleDebug"
